### ISSUE TITLE
setState causes error when opening new widgets

### ISSUE THREAD

**Issue by TheWithz** [tunitowen/fancy_bottom_navigation#5]
I'm using version 0.1.1
developing for android, I don't know if this occurs on IOS.

related to #3 
In addition to the selected icon being stuck, flutter throws an error
```
12:48:37.859 33 info flutter.tools I/flutter ( 4810): The following assertion was thrown building TickerMode(mode: disabled):

12:48:37.877 34 info flutter.tools I/flutter ( 4810): setState() or markNeedsBuild() called during build.
```

relevant stack trace

```
12:48:37.902 49 info flutter.tools I/flutter ( 4810): When the exception was thrown, this was the stack:
12:48:37.902 50 info flutter.tools I/flutter ( 4810): #0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:3485:11)
12:48:37.902 51 info flutter.tools I/flutter ( 4810): #1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:3511:6)
12:48:37.902 52 info flutter.tools I/flutter ( 4810): #2      State.setState (package:flutter/src/widgets/framework.dart:1146:14)
12:48:37.902 53 info flutter.tools I/flutter ( 4810): #3      _FancyBottomNavigationState._setSelected (package:fancy_bottom_navigation/fancy_bottom_navigation.dart:194:21)
12:48:37.902 54 info flutter.tools I/flutter ( 4810): #4      _FancyBottomNavigationState.didChangeDependencies (package:fancy_bottom_navigation/fancy_bottom_navigation.dart:64:5)
12:48:37.902 55 info flutter.tools I/flutter ( 4810): #5      StatefulElement.didChangeDependencies (package:flutter/src/widgets/framework.dart:3960:12)
12:48:37.902 56 info flutter.tools I/flutter ( 4810): #6      Element.activate (package:flutter/src/widgets/framework.dart:3054:7)
```

This error occurs when opening another widget from the body of the scaffold containing the fancy nav bar
for example, via a button.

**Comment by tunitowen** [comment]
Thanks for raising, will be looking at the linked issue very soon and will keep this in mind

**Comment by tunitowen** [comment]
Pushed to master, and version 0.2.0 on pub. All should be fixed now.
